config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/create'


  get 'home/index'

  resources :home

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  root 'home#index'
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :nickname,  :captcha  => true
  
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Scoutiste Contact",
      :to => "scoutiste@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = "We'll give you a ring shortly!"
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
      @city_array = ["Atlanta", "Austin", "Boston", "Chicago", "Charlotte", "Dallas", "Denver", "Houston", "Kansas City", "Las Vegas", "Los Angeles", "Miami", "Minneapolis", "New York", "Phoenix", "Portland", "Raleigh", "San Diego", "San Francisco", "Seattle", "St Louis", "Washington DC"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.erb
<div align="center" id="contact">
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert"></a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center" id="contact">

  <%= simple_form_for(@contact, html: { class: 'form-horizontal' }) do |f| %>

    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
        <div class= "hidden">
          <%= f.input :nickname, :hint => 'Leave this field blank!' %>
        </div>
        <div>
          <br>
          <%= f.button :submit, 'SIGN UP', :class=> "btn btn-primary" %>
        </div>
  <% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scoutiste</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 


  <div class="box">
    <div class="content">
      <div class="overlay text-center row">
          
              <span id="intro2">That Milo Baughman coffee table near you at a fire sale price?</span>
              <span id="intro3">You'll be the first to know.<br></span>
              <span id="intro5">The vintage kelly green slipper chair that would never cross your mind?</span>
              <span id="intro4">We'll show you that one, too.</span><br>
          
              <span id="intro6">We want to help you kick it up a notch, within budget.<br></span>
              <span id="intro7">We're the furniture concierge.</span><br><br>

              <span id="intro8">Launching soon. Sign up to be notified.<br></span>
          

          <div align="center"><a href="<%=contacts_new_path%>" class="btn btn-primary" role="button">SIGN UP</a>
          </div>
      </div>  
    </div>
  </div>




 

<script src="assets/nanobar.min.js"></script>
<script>
      var nanobar = new Nanobar();
      nanobar.go(100);
      
</script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scoutiste</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<nav class="navbar">
	    <div class="container-fluid">
	      <div class="navbar-header">
	        <a class="navbar-brand" href="<%=home_index_path%>">
	          <img alt="Brand" src="<%=asset_path('logo2.png')%>">
	        </a>
	      </div>
	    </div>
	</nav>
</head>
<body>

<%= yield %>
</body>
</html>